In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('ecommerce.csv')

In [3]:
df.head()

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,...,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,17.9,9.0,4.0,16.3,20.8,1.0,953.33,2278.0,0,Q1
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,42.8,7.0,3.0,NaN,23.3,3.0,1067.47,3028.0,0,Q4
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,0.0,4.0,1.0,NaN,8.8,NaN,1289.75,2317.0,0,Q4
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,41.4,2.0,5.0,85.9,31.0,3.0,2340.92,2674.0,0,Q1
4,35.0,Male,India,Delhi,3.1,29.0,51.4,NaN,19.1,9.0,...,37.9,1.0,11.0,83.0,50.4,4.0,3041.29,5354.0,0,Q4

In [4]:
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_")

In [5]:
df.shape

(50000, 25)

In [127]:
df.isnull().sum()

age                                 0
gender                              0
country                             0
city                                0
membership_years                    0
login_frequency                     0
session_duration_avg                0
pages_per_session                   0
cart_abandonment_rate               0
wishlist_items                      0
total_purchases                     0
average_order_value                 0
days_since_last_purchase            0
discount_usage_rate                 0
returns_rate                        0
email_open_rate                     0
customer_service_calls              0
product_reviews_written             0
social_media_engagement_score       0
mobile_app_usage                    0
payment_method_diversity            0
lifetime_value                      0
credit_balance                   5500
churned                             0
signup_quarter                      0
membership_years_round              0
dtype: int64

In [132]:
df.isnull().mean() * 100

age                              0.0
gender                           0.0
country                          0.0
city                             0.0
membership_years                 0.0
login_frequency                  0.0
session_duration_avg             0.0
pages_per_session                0.0
cart_abandonment_rate            0.0
wishlist_items                   0.0
total_purchases                  0.0
average_order_value              0.0
days_since_last_purchase         0.0
discount_usage_rate              0.0
returns_rate                     0.0
email_open_rate                  0.0
customer_service_calls           0.0
product_reviews_written          0.0
social_media_engagement_score    0.0
mobile_app_usage                 0.0
payment_method_diversity         0.0
lifetime_value                   0.0
credit_balance                   0.0
churned                          0.0
signup_quarter                   0.0
membership_years_round           0.0
dtype: float64

In [9]:
df.columns

Index(['age', 'gender', 'country', 'city', 'membership_years',
       'login_frequency', 'session_duration_avg', 'pages_per_session',
       'cart_abandonment_rate', 'wishlist_items', 'total_purchases',
       'average_order_value', 'days_since_last_purchase',
       'discount_usage_rate', 'returns_rate', 'email_open_rate',
       'customer_service_calls', 'product_reviews_written',
       'social_media_engagement_score', 'mobile_app_usage',
       'payment_method_diversity', 'lifetime_value', 'credit_balance',
       'churned', 'signup_quarter'],
      dtype='str')

In [10]:
df["age"].median()

np.float64(38.0)

In [11]:
df["age"]=df["age"].fillna(df["age"].median())

In [12]:
df["age"].isnull().mean()*100

np.float64(0.0)

NOW WORK ON FILL SESSION DURATION AVERAGE

In [13]:
df["session_duration_avg"].dtypes

dtype('float64')

In [14]:
df["session_duration_avg"].isnull().mean()*100

np.float64(6.798)

In [15]:
df["session_duration_avg"].median()

np.float64(26.8)

In [16]:
df["membership_years_round"] = df["membership_years"].round()

In [17]:
df.groupby("membership_years_round")["session_duration_avg"].median()

membership_years_round
0.0     26.85
1.0     27.00
2.0     26.50
3.0     26.50
4.0     26.80
5.0     26.90
6.0     26.90
7.0     26.80
8.0     26.90
9.0     27.60
10.0    27.00
Name: session_duration_avg, dtype: float64

In this transform Means in each session duration lik 0-1,1-2 missing value replace with the specific years sesion

In [18]:
df["session_duration_avg"]=df["session_duration_avg"].fillna(df.groupby
("membership_years_round")["session_duration_avg"].transform("median"))

IT is used as a Backup if still reamin any vcalue missing replace it With overall missing Values Median

In [19]:
df["session_duration_avg"]=df["session_duration_avg"].fillna(df.groupby
("membership_years_round")["session_duration_avg"].median())

In [20]:
df["session_duration_avg"].isnull().sum()

np.int64(0)

NOW HANDLE MISSING VALUE PAGES PER SESSION

In [21]:
df["pages_per_session"].dtypes

dtype('float64')

In [22]:
df["pages_per_session"].median()

np.float64(8.4)

In [23]:
df.groupby("membership_years_round")["pages_per_session"].median()

membership_years_round
0.0     8.5
1.0     8.5
2.0     8.4
3.0     8.3
4.0     8.4
5.0     8.3
6.0     8.6
7.0     8.6
8.0     8.3
9.0     9.1
10.0    8.6
Name: pages_per_session, dtype: float64

In this transform Means in each session duration lik 0-1,1-2 missing value replace with the specific years sesion

In [24]:
df["pages_per_session"]=df["pages_per_session"].fillna(df.groupby
("membership_years_round")["pages_per_session"].transform("median"))

IT is used as a Backup if still reamin any vcalue missing replace it With overall missing Values Median

In [26]:
df["pages_per_session"]=df["pages_per_session"].fillna(df.groupby
("membership_years_round")["pages_per_session"].median())

In [25]:
df["pages_per_session"].isnull().sum()

np.int64(0)

NOW HANDLE MISSING VALUE wishlist_items

In [27]:
df["wishlist_items"].dtypes

dtype('float64')

In [28]:
df["wishlist_items"].isnull().mean()*100

np.float64(8.0)

In [29]:
df["wishlist_items"].median()

np.float64(4.0)

In [30]:
df.loc[df["total_purchases"] < 0, "total_purchases"] = None

In [31]:
df.groupby("total_purchases")["wishlist_items"].median()

total_purchases
0.0      0.0
1.0      0.0
1.3      0.0
2.0      1.0
2.6      1.0
        ...
118.3    3.0
123.5    4.0
124.8    1.0
127.4    7.0
128.7    7.0
Name: wishlist_items, Length: 133, dtype: float64

In [32]:
df["wishlist_items"] = df["wishlist_items"].fillna(
    df.groupby("total_purchases")["wishlist_items"].transform("median")
)

In [33]:
df["wishlist_items"]=df["wishlist_items"].fillna(
    df["wishlist_items"].median()
)

NOW HANDLE MISSING VALUE of Total Purchase

In [ ]:
df["total_purchases"].dtypes

np.float64(12.0)

In [36]:
df["total_purchases"].median()

np.float64(12.0)

In [35]:
df["total_purchases"].isnull().mean()*100

np.float64(0.08)

In [37]:
df["total_purchases"]=df["total_purchases"].fillna(df["total_purchases"].median())

NOW HANDLE MISSING VALUE Days Since Last purchase

In [38]:
df["days_since_last_purchase"].dtypes

dtype('float64')

In [39]:
df["days_since_last_purchase"].median()

np.float64(21.0)

In [44]:
df["days_since_last_purchase"].isnull().mean()*100

np.float64(0.0)

In [ ]:
df["days_since_last_purchase"] = df["days_since_last_purchase"].fillna(
    df.groupby("total_purchases")["days_since_last_purchase"].transform("median")
)

In [43]:
df["days_since_last_purchase"] = df["days_since_last_purchase"].fillna(
    df["days_since_last_purchase"].median()
)

# Handle Missing Value of Discount_Usage_Rate

In [47]:
df["discount_usage_rate"].dtypes

dtype('float64')

In [49]:
df["discount_usage_rate"].median()

np.float64(40.2)

In [54]:
df["discount_usage_rate"].isnull().mean()*100

np.float64(0.0)

In [51]:
df["discount_usage_rate"]=df["discount_usage_rate"].fillna(
    df.groupby("total_purchases")["discount_usage_rate"].transform("median")
)

In [59]:
df["discount_usage_rate"]=df["discount_usage_rate"].fillna(
   df["discount_usage_rate"].median()
)

# Handle Missing Value of Returns_Rate

In [60]:
df["returns_rate"].dtypes

dtype('float64')

In [71]:
df["returns_rate"].isnull().mean()*100

np.float64(0.0)

In [58]:
df["returns_rate"].median()

np.float64(5.4)

In [68]:
df["returns_rate"]=df["returns_rate"].fillna(
df.groupby("total_purchases")["returns_rate"].transform("median")
)

In [70]:
df["returns_rate"]=df["returns_rate"].fillna(
df["returns_rate"].median()
)

# Handle Missing Value of Emails_Open_rate

In [ ]:
df["email_open_rate"].dtypes

dtype('float64')

In [79]:
df["email_open_rate"].isnull().mean()*100

np.float64(0.0)

In [77]:
df["email_open_rate"].median()

np.float64(19.7)

In [78]:
df["email_open_rate"]=df["email_open_rate"].median()

# Handle Missing Value of Customer_Services_calls

In [82]:
df["customer_service_calls"].dtypes

dtype('float64')

In [83]:
df["customer_service_calls"].median()

np.float64(5.0)

In [86]:
df["customer_service_calls"].isnull().mean()*100

np.float64(0.0)

In [85]:
df["customer_service_calls"]=df["customer_service_calls"].median()

# Handle Missing Value of product_reviews_written

In [89]:
df["product_reviews_written"].dtypes

dtype('float64')

In [96]:
df["product_reviews_written"].isnull().mean()*100

np.float64(0.0)

In [95]:
df["product_reviews_written"].median()

np.float64(2.0)

In [92]:
df["product_reviews_written"]=df["product_reviews_written"].fillna(
    df.groupby("total_purchases")["product_reviews_written"].transform("median")
)

In [94]:
df["product_reviews_written"]=df["product_reviews_written"].fillna(
    df["product_reviews_written"].median()
)

# Handle Missing Value of mobile_app_usage

In [99]:
df["social_media_engagement_score"].dtypes

dtype('float64')

In [100]:
df["social_media_engagement_score"].median()

np.float64(27.6)

In [106]:
df["social_media_engagement_score"].isnull().mean()*100

np.float64(0.0)

In [105]:
df["social_media_engagement_score"]=df["social_media_engagement_score"].fillna(
    df.groupby("login_frequency")["social_media_engagement_score"].transform("median")
)

In [107]:
df["social_media_engagement_score"]=df["social_media_engagement_score"].fillna(
    df["social_media_engagement_score"].median()
)

# Handle Missing Value of Social_Media_Engagement_Score

In [109]:
df["mobile_app_usage"].dtypes

dtype('float64')

In [110]:
df["mobile_app_usage"].median()

np.float64(18.6)

In [113]:
df["mobile_app_usage"].isnull().mean()*100

np.float64(0.0)

In [112]:
df["mobile_app_usage"]=df["mobile_app_usage"].fillna(
    df.groupby("login_frequency")["mobile_app_usage"].transform("median")
)

In [114]:
df["mobile_app_usage"]=df["mobile_app_usage"].fillna(
    df["mobile_app_usage"].median()
)

# Handle Missing Value of Payment_Method_Diversity

In [119]:
df["payment_method_diversity"].dtypes

dtype('float64')

In [120]:
df["payment_method_diversity"].median()

np.float64(2.0)

In [123]:
df["payment_method_diversity"].isnull().mean()*100

np.float64(0.0)

In [122]:
df["payment_method_diversity"]=df["payment_method_diversity"].fillna(
    df["payment_method_diversity"].median()
)

# Handle Missing Value of Credit_Balance

In [124]:
df["credit_balance"].dtypes

dtype('float64')

In [131]:
df["credit_balance"].isnull().mean()*100

np.float64(0.0)

In [128]:
df["credit_balance"]=df["credit_balance"].fillna(
    df.groupby("average_order_value")["credit_balance"].transform("median")
)

In [130]:
df["credit_balance"]=df["credit_balance"].fillna(
    df["credit_balance"].median()
)

------------------------------------------------------------------------------------------------

In [133]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Length: 50000, dtype: bool

In [134]:
df.duplicated().sum()

np.int64(0)

In [135]:
df["country"].value_counts()

country
USA          17384
UK            7534
Canada        6023
Germany       4925
Australia     4061
France        4013
India         3512
Japan         2548
Name: count, dtype: int64

In [136]:
df.describe()

,age,membership_years,login_frequency,session_duration_avg,pages_per_session,cart_abandonment_rate,wishlist_items,total_purchases,average_order_value,days_since_last_purchase,...,email_open_rate,customer_service_calls,product_reviews_written,social_media_engagement_score,mobile_app_usage,payment_method_diversity,lifetime_value,credit_balance,churned,membership_years_round
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.00000,...,5.000000e+04,50000.0,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.00000
mean,37.812800,2.984009,11.624660,27.598456,8.718796,57.079973,4.283840,13.12616,123.117330,29.24844,...,1.970000e+01,5.0,2.839940,29.235878,19.358945,2.33618,1440.626292,1961.978520,0.289000,2.98154
std,11.535688,2.059105,7.810657,10.497699,3.663989,16.282723,3.116451,6.99548,175.569714,28.87451,...,3.552749e-15,0.0,2.278079,19.820447,9.165734,1.08465,907.249443,1186.217664,0.453302,2.08537
min,5.000000,0.100000,0.000000,1.000000,1.000000,0.000000,0.000000,0.00000,26.380000,0.00000,...,1.970000e+01,5.0,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.00000
25%,30.000000,1.400000,6.000000,20.200000,6.200000,46.400000,2.000000,8.00000,87.050000,9.00000,...,1.970000e+01,5.0,1.000000,14.400000,12.700000,2.00000,789.817500,1101.375000,0.000000,1.00000
50%,38.000000,2.500000,11.000000,26.800000,8.400000,58.100000,4.000000,12.00000,112.970000,21.00000,...,1.970000e+01,5.0,2.000000,27.300000,18.500000,2.00000,1243.415000,1896.000000,0.000000,2.00000
75%,45.000000,4.000000,17.000000,34.000000,11.000000,68.700000,6.000000,17.00000,144.440000,39.00000,...,1.970000e+01,5.0,4.000000,42.300000,25.300000,3.00000,1874.000000,2737.625000,1.000000,4.00000
max,200.000000,10.000000,46.000000,75.600000,24.100000,143.743350,28.000000,128.70000,9666.379178,287.00000,...,1.970000e+01,5.0,21.000000,100.000000,61.900000,5.00000,8987.240000,7197.000000,1.000000,10.00000

In [137]:
df.to_csv("cleaned_ecommerce.csv", index=False)